#!/bin/sh

echo "-- Building source package"
VERSION=`head -1 ChangeLog | cut -f2 -d"(" | cut -f1 -d")"`
touch firetable-${VERSION}.tar.gz
cd ..
ln -s firetable firetable-${VERSION}
tar --exclude=*.tar.gz --exclude=*.deb -czhf firetable/firetable-${VERSION}.tar.gz firetable-${VERSION}
rm firetable-${VERSION}
